services:
  homestream:
    build: ./backend
    container_name: homestream
    restart: unless-stopped
    ports:
      - "9091:9090"
    volumes:
      - ./config:/config
      - homestream-data:/data
    environment:
      - TZ=Europe/Moscow

volumes:
  homestream-data:
